// Schémas partagés front/back : la même règle valide le formulaire et le body de l'API.
// Imports relatifs avec l'extension .ts, uniquement de la syntaxe effaçable (pas d'enum, pas de namespace).
export * from './common/email.field.ts'
export * from './common/new-password.field.ts'
export * from './auth/login.dto.ts'
export * from './users/create-user.dto.ts'
export * from './users/user.dto.ts'
export * from './health/health.dto.ts'
export * from './common/number.field.ts'
export * from './purchases/save-purchase.dto.ts'
export * from './purchases/purchase.dto.ts'
export * from './portfolio/trend.dto.ts'
export * from './portfolio/quote.dto.ts'
export * from './portfolio/position.dto.ts'
export * from './portfolio/portfolio.dto.ts'
export * from './portfolio/asset.dto.ts'
export * from './watchlist/save-watch.dto.ts'
export * from './watchlist/watch.dto.ts'
